<a href="https://colab.research.google.com/github/Shivanuli/shiva-DA/blob/main/scipy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from scipy) (1.25.2)

In [2]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.1)
Requirement already satisfied: numpy<2,>=1.18 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.25.2)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.11.4)
Requirement already satisfied: pandas!=2.1.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.5.3)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.0->statsmodels) (2023.4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels) (1.16.0)

In [3]:
#import libraries
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm

In [8]:
#upload csv file
df=pd.read_excel("/content/Copy of E-Bill (1).xlsx")
df.head(18)

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Year,Month,Bill Date,Amount,Unnamed: 4,Calculation Table,Unnamed: 6,Unnamed: 7,Year.1,Paid,Average
0,2020.0,April,2020-04-16,1283.0,NaN,Total Average,6139.277778,NaN,2020,25102,5020.400000
1,2020.0,June,2020-06-14,5419.0,NaN,Total,110507.000000,NaN,April,1283,1283.000000
2,2020.0,August,2020-08-14,7284.0,NaN,Min,375.000000,NaN,June,5419,5419.000000
3,2020.0,October,2020-10-11,10741.0,NaN,Max,15359.000000,NaN,August,7284,7284.000000
4,2020.0,December,2020-12-05,375.0,NaN,NaN,NaN,NaN,October,10741,10741.000000
5,2021.0,February,2021-02-14,2074.0,NaN,NaN,NaN,NaN,December,375,375.000000
6,2021.0,April,2021-04-10,1225.0,NaN,NaN,NaN,NaN,2021,33763,5627.166667
7,2021.0,June,2021-06-05,4869.0,NaN,NaN,NaN,NaN,February,2074,2074.000000
8,2021.0,August,2021-08-06,14113.0,NaN,NaN,NaN,NaN,April,1225,1225.000000
9,2021.0,October,2021-10-14,10059.0,NaN,NaN,NaN,NaN,June,4869,4869.000000
10,2021.0,December,2021-10-10,1423.0,NaN,NaN,NaN,NaN,August,14113,14113.000000
11,2022.0,February,2022-02-08,1855.0,NaN,NaN,NaN,NaN,October,10059,10059.000000
12,2022.0,April,2022-02-09,1335.0,NaN,NaN,NaN,NaN,December,1423,1423.000000
13,2022.0,June,2022-06-09,12076.0,NaN,NaN,NaN,NaN,2022,48374,8062.333333
14,2022.0,August,2022-08-08,15359.0,NaN,NaN,NaN,NaN,February,1855,1855.000000
15,2022.0,October,2022-10-08,14502.0,NaN,NaN,NaN,NaN,April,1335,1335.000000
16,2022.0,December,2022-12-07,3247.0,NaN,NaN,NaN,NaN,June,12076,12076.000000
17,2023.0,February,2023-12-06,3268.0,NaN,NaN,NaN,NaN,August,15359,15359.000000

In [9]:
df_reqcol=['Year','Amount']
df_req=df[df_reqcol]
df_req

      Year   Amount
0   2020.0   1283.0
1   2020.0   5419.0
2   2020.0   7284.0
3   2020.0  10741.0
4   2020.0    375.0
5   2021.0   2074.0
6   2021.0   1225.0
7   2021.0   4869.0
8   2021.0  14113.0
9   2021.0  10059.0
10  2021.0   1423.0
11  2022.0   1855.0
12  2022.0   1335.0
13  2022.0  12076.0
14  2022.0  15359.0
15  2022.0  14502.0
16  2022.0   3247.0
17  2023.0   3268.0
18     NaN      NaN
19     NaN      NaN
20     NaN      NaN
21     NaN      NaN
22     NaN      NaN

In [12]:
df2=df_req.dropna()
df2

      Year   Amount
0   2020.0   1283.0
1   2020.0   5419.0
2   2020.0   7284.0
3   2020.0  10741.0
4   2020.0    375.0
5   2021.0   2074.0
6   2021.0   1225.0
7   2021.0   4869.0
8   2021.0  14113.0
9   2021.0  10059.0
10  2021.0   1423.0
11  2022.0   1855.0
12  2022.0   1335.0
13  2022.0  12076.0
14  2022.0  15359.0
15  2022.0  14502.0
16  2022.0   3247.0
17  2023.0   3268.0

In [13]:
df2.to_csv('p1.csv')

In [ ]:
df3=pd.read_csv('/content/p1.csv')

In [26]:
np.random.seed(0)
df4 = pd.DataFrame({
    'Year': np.random.choice(['2020', '2021', '2022'],size=18),
    'Amount':np.random.normal(loc=10, scale=2, size=18)#loc=>mean,scale=>standard deviation
})
print(df4)

    Year     Amount
0   2020   9.058458
1   2021  11.946032
2   2020   7.443702
3   2021  12.874741
4   2021   9.844591
5   2022  12.179260
6   2020  10.193085
7   2022  12.837334
8   2020  12.336546
9   2020  11.894372
10  2020  12.170974
11  2022  14.764449
12  2021   9.187953
13  2022  10.532891
14  2022   7.288573
15  2020   9.771795
16  2021   8.311538
17  2021  11.411282

In [17]:
#claculate mean amount for each year
mean_score_per_group = df4.groupby('Year')['Amount'].mean()
print(mean_score_per_group)

Year
2020    10.409847
2021    10.596023
2022    11.520501
Name: Amount, dtype: float64

In [18]:
#generate random year selections
choices = ['2020', '2021', '2022']
size = 18
year_column = np.random.choice(choices, size=size)
print(year_column)

['2020' '2020' '2020' '2021' '2021' '2022' '2020' '2020' '2021' '2020'
 '2021' '2022' '2022' '2020' '2021' '2021' '2021' '2021']

In [19]:
#calculate amount values
mean = 10
std = 2
size = 18
Amount_values = mean + std * np.random.randn(size)
print(Amount_values)

[12.46058136 12.4047597   9.22534637  9.3953945   7.90289407  7.15996413
  6.58745962 13.90155079  8.98069564  9.1238514   7.49440928 11.55498071
  6.7722043   9.57451944  8.20906688 10.773805    8.97838972  7.63873563]

In [21]:
# hypothesis testing (t-test)
group_A = df4[df4['Year'] == '2020']['Amount']
group_B = df4[df4['Year'] == '2021']['Amount']
t_stat, p_value =stats.ttest_ind(group_A, group_B)
print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: -0.18616648409089434
p-value: 0.8557029463822119

In [22]:
#prediction
if p_value < 0.05:
  print("reject the null hypothesis")
else:
  print("fail to reject the null hypothesis")

fail to reject the null hypothesis

In [24]:
#ANOVA (one-way ANOVA)
f_stat, p_value = stats.f_oneway(df4[df4['Year']== '2020']['Amount'],
                                 df4[df4['Year']== '2021']['Amount'],
                                 df4[df4['Year']== '2022']['Amount'])
print("F-statistic:",f_stat)
print("p-value:",p_value)

F-statistic: 0.43623602109638376
p-value: 0.6544103539964587